### ISSUE TITLE
Replace `_.cloneDeep()` with `structuredClone()`

### ISSUE THREAD

**Issue by LukeStanbery89** [theScottyJam/snap.js#1]
Lodash's [cloneDeep](https://lodash.com/docs/#cloneDeep) function can be replaced by [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone).

**Comment by theScottyJam** [comment]
Thanks for the suggestion - I'll get a page put together explaining `structuredClone()`.

**Comment by theScottyJam** [comment]
I added an entry for cloneDeep in https://github.com/theScottyJam/snap.js/commit/5995db1b3bb4a462e428f71e808fefd2722bbcd3 and pushed the changes live. You can view the page here: https://thescottyjam.github.io/snap.js/#!/nolodash/cloneDeep

I'll go ahead and close this, but feel free to re-open (or open a new ticket) if you have any additional feedback.

**Comment by LukeStanbery89** [comment]
Great work! 😄
