### ISSUE TITLE
License

### ISSUE THREAD

**Issue by psmolak** [theScottyJam/snap.js#9]
Good morning sir,

I love your approach and the lodash replecements.

Is there any chance for distributing your code with a license? Currently there's none and I'm not sure whether I can use this piece of art of yours in my own projects.

Cheers,
Paweł.

**Comment by theScottyJam** [comment]
In the website's footer, it mentions that all code being shown is under the MIT license.

Would you like me to also add that information in another place? Perhaps a license file in the repo?

**Comment by theScottyJam** [comment]
I ended up adding a LICENSE file, and changing the license to "unlicense".

Didn't realize that MIT still required attribution, which sound obnoxious for copy-paste utilities. The unlicense license seems to be a little more liberal and lifts that requirement.
